# the pipeline is to have the raw data here and clean it
# then move it to cleaned config
# the rAW data are from the notebooks cleaning_Preproceeesing folder
rawdatapath:
    DataFolder: /Dataset/
    dataFileName: human_cachexia.csv
    